# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Deploy application
 
on:
  push:
    branches: [ buildFrontend ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy React app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.IP_ADRESS}}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            pm2 start app.js # start as a background service.
